// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurismoConecta.api.Data;

#nullable disable

namespace TurismoConecta.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Modern_Spanish_CI_AI")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TurismoConecta.api.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Icono")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("icono");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__8A3D240C145FC97D");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Categori__72AFBCC62B055AE0")
                        .IsUnique();

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDepartamento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Colombia")
                        .HasColumnName("pais");

                    b.HasKey("IdDepartamento")
                        .HasName("PK__Departam__C225F98D7F570F44");

                    b.ToTable("Departamento", (string)null);
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Etiqueta", b =>
                {
                    b.Property<int>("IdEtiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEtiqueta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEtiqueta"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEtiqueta");

                    b.ToTable("Etiqueta");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Favorito", b =>
                {
                    b.Property<int>("IdFavorito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idFavorito");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFavorito"));

                    b.Property<DateTime>("FechaGuardado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaGuardado")
                        .HasDefaultValueSql("(sysdatetime())", "DF_Favorito_fechaGuardado");

                    b.Property<int?>("IdMunicipio")
                        .HasColumnType("int")
                        .HasColumnName("idMunicipio");

                    b.Property<int?>("IdNegocio")
                        .HasColumnType("int")
                        .HasColumnName("idNegocio");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.HasKey("IdFavorito");

                    b.HasIndex("IdMunicipio");

                    b.HasIndex("IdNegocio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Favorito", (string)null);
                });

            modelBuilder.Entity("TurismoConecta.api.Models.GaleriaNegocio", b =>
                {
                    b.Property<int>("IdGaleria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idGaleria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGaleria"));

                    b.Property<int>("IdNegocio")
                        .HasColumnType("int")
                        .HasColumnName("idNegocio");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("imagenUrl");

                    b.HasKey("IdGaleria")
                        .HasName("PK__GaleriaN__F48A5B5461E947ED");

                    b.HasIndex("IdNegocio");

                    b.ToTable("GaleriaNegocio", (string)null);
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Itinerario", b =>
                {
                    b.Property<int>("IdItinerario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idItinerario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItinerario"));

                    b.Property<Guid>("CodigoCompartir")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("codigoCompartir")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Compartido")
                        .HasColumnType("bit")
                        .HasColumnName("compartido");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fechaFin");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fechaInicio");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdItinerario")
                        .HasName("PK__Itinerar__B201E2D6E29D1263");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Itinerario", (string)null);
                });

            modelBuilder.Entity("TurismoConecta.api.Models.ItinerarioDetalle", b =>
                {
                    b.Property<int>("IdItinerarioDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idItinerarioDetalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItinerarioDetalle"));

                    b.Property<int>("DiaNumero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("diaNumero");

                    b.Property<decimal?>("DistanciaKm")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("distanciaKm");

                    b.Property<DateOnly?>("FechaVisita")
                        .HasColumnType("date")
                        .HasColumnName("fechaVisita");

                    b.Property<int>("IdItinerario")
                        .HasColumnType("int")
                        .HasColumnName("idItinerario");

                    b.Property<int>("IdMunicipio")
                        .HasColumnType("int")
                        .HasColumnName("idMunicipio");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("orden");

                    b.Property<int?>("TiempoEstimadoMin")
                        .HasColumnType("int")
                        .HasColumnName("tiempoEstimadoMin");

                    b.HasKey("IdItinerarioDetalle")
                        .HasName("PK__Itinerar__CCC310BCE5DA3F0B");

                    b.HasIndex("IdItinerario");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("ItinerarioDetalle", (string)null);
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Municipio", b =>
                {
                    b.Property<int>("IdMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMunicipio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMunicipio"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Clima")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("clima");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("FechasRelevantes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fechasRelevantes");

                    b.Property<string>("Historia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("historia");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int")
                        .HasColumnName("idDepartamento");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("imagenUrl");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(9, 6)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(9, 6)")
                        .HasColumnName("longitud");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdMunicipio")
                        .HasName("PK__Municipi__FD10E40022C53579");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("Municipio", (string)null);
                });

            modelBuilder.Entity("TurismoConecta.api.Models.MunicipioEtiqueta", b =>
                {
                    b.Property<int>("IdMunicipioEtiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMunicipioEtiqueta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMunicipioEtiqueta"));

                    b.Property<int>("IdEtiqueta")
                        .HasColumnType("int")
                        .HasColumnName("idEtiqueta");

                    b.Property<int>("IdMunicipio")
                        .HasColumnType("int")
                        .HasColumnName("idMunicipio");

                    b.HasKey("IdMunicipioEtiqueta");

                    b.HasIndex("IdEtiqueta");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("MunicipioEtiqueta");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Negocio", b =>
                {
                    b.Property<int>("IdNegocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idNegocio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNegocio"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado")
                        .HasDefaultValue("Pendiente", "DF_Negocio_estado");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaAprobacion");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaRegistro");

                    b.Property<string>("Horario")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("horario");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    b.Property<int>("IdMunicipio")
                        .HasColumnType("int")
                        .HasColumnName("idMunicipio");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<string>("ImagenPrincipalUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("imagenPrincipalUrl");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(9, 6)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(9, 6)")
                        .HasColumnName("longitud");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("IdNegocio");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdMunicipio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Negocio", (string)null);
                });

            modelBuilder.Entity("TurismoConecta.api.Models.NegocioEtiqueta", b =>
                {
                    b.Property<int>("IdNegocioEtiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idNegocioEtiqueta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNegocioEtiqueta"));

                    b.Property<int>("IdEtiqueta")
                        .HasColumnType("int")
                        .HasColumnName("idEtiqueta");

                    b.Property<int>("IdNegocio")
                        .HasColumnType("int")
                        .HasColumnName("idNegocio");

                    b.HasKey("IdNegocioEtiqueta");

                    b.HasIndex("IdEtiqueta");

                    b.HasIndex("IdNegocio");

                    b.ToTable("NegocioEtiqueta");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idNotificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("IdTipoNotificacion")
                        .HasColumnType("int")
                        .HasColumnName("idTipoNotificacion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit")
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mensaje");

                    b.HasKey("IdNotificacion")
                        .HasName("PK__Notifica__AFE1D7E4960044C0");

                    b.HasIndex("IdTipoNotificacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Notificacion", (string)null);
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Reseña", b =>
                {
                    b.Property<int>("IdReseña")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idReseña");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReseña"));

                    b.Property<byte>("Calificacion")
                        .HasColumnType("tinyint")
                        .HasColumnName("calificacion");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaRespuesta");

                    b.Property<int?>("IdMunicipio")
                        .HasColumnType("int")
                        .HasColumnName("idMunicipio");

                    b.Property<int?>("IdNegocio")
                        .HasColumnType("int")
                        .HasColumnName("idNegocio");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<bool>("Moderada")
                        .HasColumnType("bit")
                        .HasColumnName("moderada");

                    b.Property<string>("Respuesta")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("respuesta");

                    b.HasKey("IdReseña");

                    b.HasIndex("IdMunicipio");

                    b.HasIndex("IdNegocio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reseña", (string)null);
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__3C872F76177276D9");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Rol__72AFBCC66E08C31C")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("TurismoConecta.api.Models.TiposNotificacion", b =>
                {
                    b.Property<int>("IdTipoNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTipoNotificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoNotificacion"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdTipoNotificacion")
                        .HasName("PK__TiposNot__6F70CA63E933ECF1");

                    b.HasIndex(new[] { "Codigo" }, "UQ__TiposNot__40F9A206DA8B2BA4")
                        .IsUnique();

                    b.ToTable("TiposNotificacion", (string)null);
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("bit")
                        .HasColumnName("emailConfirmado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaRegistro")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FotoUrl");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("idRol");

                    b.Property<int?>("MunicipioAsignadoId")
                        .HasColumnType("int")
                        .HasColumnName("municipioAsignadoId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("passwordHash");

                    b.Property<DateTime?>("PasswordResetExpira")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__645723A6F4DEE701");

                    b.HasIndex("IdRol");

                    b.HasIndex("MunicipioAsignadoId");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuario__AB6E6164279433C1")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Favorito", b =>
                {
                    b.HasOne("TurismoConecta.api.Models.Municipio", "IdMunicipioNavigation")
                        .WithMany("Favoritos")
                        .HasForeignKey("IdMunicipio")
                        .HasConstraintName("FK_Favorito_Municipio");

                    b.HasOne("TurismoConecta.api.Models.Negocio", "IdNegocioNavigation")
                        .WithMany("Favoritos")
                        .HasForeignKey("IdNegocio")
                        .HasConstraintName("FK_Favorito_Negocio");

                    b.HasOne("TurismoConecta.api.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Favoritos")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Favorito_Usuario");

                    b.Navigation("IdMunicipioNavigation");

                    b.Navigation("IdNegocioNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.GaleriaNegocio", b =>
                {
                    b.HasOne("TurismoConecta.api.Models.Negocio", "IdNegocioNavigation")
                        .WithMany("GaleriaNegocios")
                        .HasForeignKey("IdNegocio")
                        .IsRequired()
                        .HasConstraintName("FK_GaleriaNegocio_Negocio");

                    b.Navigation("IdNegocioNavigation");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Itinerario", b =>
                {
                    b.HasOne("TurismoConecta.api.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Itinerarios")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Itinerarios_Usuarios");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.ItinerarioDetalle", b =>
                {
                    b.HasOne("TurismoConecta.api.Models.Itinerario", "IdItinerarioNavigation")
                        .WithMany("ItinerarioDetalles")
                        .HasForeignKey("IdItinerario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ItinerarioDetalle_Itinerarios");

                    b.HasOne("TurismoConecta.api.Models.Municipio", "IdMunicipioNavigation")
                        .WithMany("ItinerarioDetalles")
                        .HasForeignKey("IdMunicipio")
                        .IsRequired()
                        .HasConstraintName("FK_ItinerarioDetalle_Municipios");

                    b.Navigation("IdItinerarioNavigation");

                    b.Navigation("IdMunicipioNavigation");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Municipio", b =>
                {
                    b.HasOne("TurismoConecta.api.Models.Departamento", "IdDepartamentoNavigation")
                        .WithMany("Municipios")
                        .HasForeignKey("IdDepartamento")
                        .IsRequired()
                        .HasConstraintName("FK_Municipios_Departamentos");

                    b.Navigation("IdDepartamentoNavigation");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.MunicipioEtiqueta", b =>
                {
                    b.HasOne("TurismoConecta.api.Models.Etiqueta", "IdEtiquetaNavigation")
                        .WithMany("MunicipioEtiqueta")
                        .HasForeignKey("IdEtiqueta")
                        .IsRequired()
                        .HasConstraintName("FK_MunicipioEtiqueta_Etiqueta");

                    b.HasOne("TurismoConecta.api.Models.Municipio", "IdMunicipioNavigation")
                        .WithMany("MunicipioEtiqueta")
                        .HasForeignKey("IdMunicipio")
                        .IsRequired()
                        .HasConstraintName("FK_MunicipioEtiqueta_Municipio");

                    b.Navigation("IdEtiquetaNavigation");

                    b.Navigation("IdMunicipioNavigation");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Negocio", b =>
                {
                    b.HasOne("TurismoConecta.api.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Negocios")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Negocio_Categoria");

                    b.HasOne("TurismoConecta.api.Models.Municipio", "IdMunicipioNavigation")
                        .WithMany("Negocios")
                        .HasForeignKey("IdMunicipio")
                        .IsRequired()
                        .HasConstraintName("FK_Negocio_Municipio");

                    b.HasOne("TurismoConecta.api.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Negocios")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_Negocio_Usuario");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdMunicipioNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.NegocioEtiqueta", b =>
                {
                    b.HasOne("TurismoConecta.api.Models.Etiqueta", "IdEtiquetaNavigation")
                        .WithMany("NegocioEtiqueta")
                        .HasForeignKey("IdEtiqueta")
                        .IsRequired()
                        .HasConstraintName("FK_NegocioEtiqueta_Etiqueta");

                    b.HasOne("TurismoConecta.api.Models.Negocio", "IdNegocioNavigation")
                        .WithMany("NegocioEtiqueta")
                        .HasForeignKey("IdNegocio")
                        .IsRequired()
                        .HasConstraintName("FK_NegocioEtiqueta_Negocio");

                    b.Navigation("IdEtiquetaNavigation");

                    b.Navigation("IdNegocioNavigation");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Notificacion", b =>
                {
                    b.HasOne("TurismoConecta.api.Models.TiposNotificacion", "IdTipoNotificacionNavigation")
                        .WithMany("Notificacions")
                        .HasForeignKey("IdTipoNotificacion")
                        .IsRequired()
                        .HasConstraintName("FK_Notificaciones_Tipos");

                    b.HasOne("TurismoConecta.api.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Notificacions")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Notificaciones_Usuarios");

                    b.Navigation("IdTipoNotificacionNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Reseña", b =>
                {
                    b.HasOne("TurismoConecta.api.Models.Municipio", "IdMunicipioNavigation")
                        .WithMany("Reseñas")
                        .HasForeignKey("IdMunicipio")
                        .HasConstraintName("FK_Reseña_Municipio");

                    b.HasOne("TurismoConecta.api.Models.Negocio", "IdNegocioNavigation")
                        .WithMany("Reseñas")
                        .HasForeignKey("IdNegocio")
                        .HasConstraintName("FK_Reseña_Negocio");

                    b.HasOne("TurismoConecta.api.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Reseñas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Reseña_Usuario");

                    b.Navigation("IdMunicipioNavigation");

                    b.Navigation("IdNegocioNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Usuario", b =>
                {
                    b.HasOne("TurismoConecta.api.Models.Rol", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Roles");

                    b.HasOne("TurismoConecta.api.Models.Municipio", "MunicipioAsignado")
                        .WithMany("Usuarios")
                        .HasForeignKey("MunicipioAsignadoId")
                        .HasConstraintName("FK_Usuarios_Municipios");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("MunicipioAsignado");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Categoria", b =>
                {
                    b.Navigation("Negocios");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Etiqueta", b =>
                {
                    b.Navigation("MunicipioEtiqueta");

                    b.Navigation("NegocioEtiqueta");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Itinerario", b =>
                {
                    b.Navigation("ItinerarioDetalles");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Municipio", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("ItinerarioDetalles");

                    b.Navigation("MunicipioEtiqueta");

                    b.Navigation("Negocios");

                    b.Navigation("Reseñas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Negocio", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("GaleriaNegocios");

                    b.Navigation("NegocioEtiqueta");

                    b.Navigation("Reseñas");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.TiposNotificacion", b =>
                {
                    b.Navigation("Notificacions");
                });

            modelBuilder.Entity("TurismoConecta.api.Models.Usuario", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Itinerarios");

                    b.Navigation("Negocios");

                    b.Navigation("Notificacions");

                    b.Navigation("Reseñas");
                });
#pragma warning restore 612, 618
        }
    }
}
